name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    # خطوة لتحديث build.gradle في حال عدم احتوائه على google() و mavenCentral()
    - name: Update build.gradle repositories
      run: |
        echo "Updating build.gradle to include google() and mavenCentral()"
        # تأكد من وجود google() و mavenCentral() في repositories
        if ! grep -q "google()" build.gradle; then
          echo "Adding google() repository to build.gradle"
          sed -i '/repositories {/a \ \ \ \ google()' build.gradle
        fi
        if ! grep -q "mavenCentral()" build.gradle; then
          echo "Adding mavenCentral() repository to build.gradle"
          sed -i '/repositories {/a \ \ \ \ mavenCentral()' build.gradle
        fi

    # خطوة لإنشاء Gradle Wrapper مع تهيئة Gradle وإعداد مشروع Android
    - name: Initialize Gradle project for Android
      run: |
        if [ ! -f "build.gradle" ]; then
          echo "Creating build.gradle and gradle wrapper for Android project"
          gradle init --type java-application --overwrite
          ./gradlew wrapper
        fi

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build APK
      run: ./gradlew assembleDebug

    - name: Check APK exists
      run: ls -la app/build/outputs/apk/debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
